CREATE DATABASE Minions

USE Minions

CREATE TABLE Minions
(
Id INT NOT NULL,
Name VARCHAR(50) NOT NULL,
Age INT NOT NULL
)

CREATE TABLE Towns
(
Id INT,
Name VARCHAR(50) NOT NULL
)

ALTER TABLE Minions
ADD CONSTRAINT PK_MinionId
PRIMARY KEY (Id)

ALTER TABLE Minions
DROP CONSTRAINT PK_Id

ALTER TABLE Towns
ALTER COLUMN Id INT NOT NULL

ALTER TABLE Towns
ADD CONSTRAINT PK_TownId
PRIMARY KEY (Id)

ALTER TABLE Minions
ADD TownId INT FOREIGN KEY REFERENCES Towns

INSERT INTO Towns VALUES
(1, 'Sofia'),
(2, 'Plovdiv'),
(3, 'Varna')

ALTER TABLE Minions
ALTER COLUMN Age INT NULL

INSERT INTO Minions VALUES
(1, 'Kevin', 22, 1),
(2, 'Bob', 15, 3),
(3, 'Steward', NULL, 2)

TRUNCATE TABLE Minions

DROP TABLE Minions, Towns